services:
  atuin:
    restart: always
    image: ghcr.io/atuinsh/atuin:18.3.0
    command: server start
    depends_on:
      - postgresql
    networks: 
       default:
    env_file:
      - .env

  postgresql:
    image: postgres:14
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${ATUIN_DB_DATA}:/var/lib/postgresql/data/
    networks: 
      default:

networks:
  default:

